### PR TITLE
v2: Add flattened tweet format function

### PR DESCRIPTION
**Pull request by igorbrigadir**
This adds a function that takes an entire page of results, and inserts all `includes` inline into tweets.

### CODE REVIEW

**Comment by edsu** [comment]
Thanks @igorbrigadir this is perfect. I'll add some tests for it, and try to integrate it with @SamHames' sample method.

**Comment by edsu** [comment]
I did end up integrating it into the Twarc2.sample. I think I found a bug in the "geo" handling so an extra set of eyes on what I did would be helpful.

**Comment by igorbrigadir** [comment]
Oh thanks! I'll have a look again, I had some tweet examples to add to the repo to use as tests so those should work.

There's also a geo thing with standard and academic access where it's not returned in standard, so there might be a check needed for that, but i need to double check that.

**Comment by edsu** [comment]
I like the idea of crafting the tests to use live data rather than canned where possible.

**Comment by igorbrigadir** [comment]
> I like the idea of crafting the tests to use live data rather than canned where possible.

Sure, in that case - maybe i can see if i can find some queries to "search" so that they have a high probability of hitting some tweets with geo / media expansions and other features like that.

**Pull request merged**
