### PR TITLE
Pin dependencies

### LINKED ISSUE #533: Installation of twarc2 using pip doesn't checks for requirements version
I installed twarc on Windows using
`python -m pip install twarc`

and while running the twarc2 associated commands, I received an error that said:

No method found: some method name in `click`, 

Then I checked my `click` package, and it didn't have this method that twarc2 uses, because the version of my `click` package was not the latest one and lacked the required method.

After upgrading `click`, I was able to run twarc2 associated commands without any bugs, which led me to wonder if twarc installation using `pip` checks for the version of required dependencies or not because if it did, then my `click` package should have been upgraded too as a part of the requirements check during twarc installation. 

So, a version check of the requirements while installing using pip can solve this issue for others.

### PR DESCRIPTION
**Pull request by igorbrigadir**
Fix #533 - hopefully these won't break anything. Click has to be 7, not latest 8 because of mkdocs

### CODE REVIEW

**Comment by igorbrigadir** [comment]
Would be good for someone else to verify that these versions work - i tested it in my environment and it seemed to work.

**Comment by SamHames** [comment]
I will test on Monday, but I'd suggest setting minimum package versions
(>=)  not specific versions - twarc depends on a few fairly common packages
so we should be careful not to constrain more than necessary.

**Comment by edsu** [comment]
So mkdocs and click 8 don't mix?

**Comment by igorbrigadir** [comment]
I relaxed the requirements a bit more, and I tried it again, and it seems to work with 8 with mkdocs! i can run `mkdocs build` without errors.

For reference, in a fresh `3.8.6` Python environment, after running `pip intall --upgrade -r requirements.txt` i end up with:

```
Package            Version
------------------ ---------
certifi            2021.5.30
charset-normalizer 2.0.4
click              8.0.1
click-config-file  0.6.0
click-plugins      1.1.1
configobj          5.0.6
humanize           3.11.0
idna               3.2
oauthlib           3.1.1
pip                21.2.4
python-dateutil    2.8.2
requests           2.26.0
requests-oauthlib  1.3.0
setuptools         49.2.1
six                1.16.0
tqdm               4.62.2
urllib3            1.26.6
```

and with `requirements-mkdocs.txt`

```
Package                    Version
-------------------------- ---------
astunparse                 1.6.3
certifi                    2021.5.30
charset-normalizer         2.0.4
click                      8.0.1
click-config-file          0.6.0
click-plugins              1.1.1
configobj                  5.0.6
ghp-import                 2.0.1
humanize                   3.11.0
idna                       3.2
importlib-metadata         4.8.1
Jinja2                     3.0.1
Markdown                   3.3.4
MarkupSafe                 2.0.1
mergedeep                  1.3.4
mkdocs                     1.2.2
mkdocs-autorefs            0.2.1
mkdocs-click               0.4.0
mkdocs-material            7.2.6
mkdocs-material-extensions 1.0.3
mkdocstrings               0.15.2
oauthlib                   3.1.1
packaging                  21.0
pip                        21.2.4
Pygments                   2.10.0
pymdown-extensions         8.2
pyparsing                  2.4.7
python-dateutil            2.8.2
pytkdocs                   0.11.1
PyYAML                     5.4.1
pyyaml_env_tag             0.1
requests                   2.26.0
requests-oauthlib          1.3.0
setuptools                 49.2.1
six                        1.16.0
tqdm                       4.62.2
urllib3                    1.26.6
watchdog                   2.1.5
wheel                      0.37.0
zipp                       3.5.0
```

**Comment by SamHames** [comment]
Seems to be all working for me  - thanks for the work :)

If we do run into users with issues it should be easy to relax some of those lower bounds as well - it's much easier to change one problematic dependency at a time.

**Comment by SamHames** [comment]
Is there any reason not to merge this?

**Review by edsu — COMMENTED** [review]
This was reviewed a long time ago.

**Pull request merged**
