### PR TITLE
Made utils a package so that can be re-used.

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
In my case, I want to re-use json2csv.

**Comment by edsu** [comment]
Hmm, I'm kind of reluctant to bring the whole kitchen sink into twarc itself. The idea (which I never properly expressed) was to treat it as a laboratory for ideas that could be pulled into twarc proper. This happened with replies for example.

#172 is about adding CSV output to twarc. This would necessarily bring csv2json into the twarc module in some form. If I prioritized doing this would it satisfy your use case, or were you wanting more of utils to be available upon install?

**Comment by justinlittman** [comment]
That would work for me.

**Comment by edsu** [comment]
@justinlittman when you have a chance can you take a look at what's on master, specifically `twarc.json2csv` now and see if it works for you?

**Comment by justinlittman** [comment]
Looking.

**Comment by edsu** [comment]
This is no longer needed since CSV functionality has been made part of the twarc module.

**Pull request closed without merging**
