### PR TITLE
Add kiswahili

### PR DESCRIPTION
**Pull request by kayiwa**
This is Kenyan Kiswahili and will have colloquialisms that won't translate. I also updated the URI of unshrtn which was pointing to @edsu repo on github.

### CODE REVIEW

**Comment by edsu** [comment]
Awesome thanks @kayiwa. Can you merge the latest from master? It looks like you've added `EADME_sw-KE.md` too, and have added a `README_es.md` with 'blah blah' in it?

**Comment by kayiwa** [comment]
Oh! Sorry. I was using that to help @tinafigueroa get comfortable with PR's. It's gone now.

**Comment by edsu** [comment]
I'm still a bit confused why README_sw-KE.md is added in this PR. But I guess you merged that in from upstream from master, and that's how it shows up?

**Comment by edsu** [comment]
🎉

**Pull request merged**
