### PR TITLE
Flatten Refactor

### PR DESCRIPTION
**Pull request by igorbrigadir**
This is just missing some more tests. I changed the ensure_flatten function to hopefully be easier to understand and use. Before it would fail if presented with a list of user objects, because it relied on checking for `author` field - which won't exist in user objects.

### CODE REVIEW

**Comment by igorbrigadir** [comment]
I think this works for all types of data now, but may need a second pair of eyes / some more examples to test.

**Comment by edsu** [comment]
This looks good to me @igorbrigadir although I haven't looked closely at it. If the test_flatten() unit test passes that's a good sign. I wonder if we might need another test case for passing in User objects (I didn't realize it could work with those).

**Comment by igorbrigadir** [comment]
Ah - i did find a problem - looks like it is better to let it pass without error if there's `data` but no `includes`. `flatten()` can handle this just fine - and it's a valid API response.

For example:

```
twarc2 following overflow64 | twarc2 flatten
```

should work.

**Comment by igorbrigadir** [comment]
Ok, that took slightly more changes - so now, i think it finally covers all cases:

A single response where data is a dict (eg: stream)
A single response where data is a list (eg: search)
A list of responses where data is a dict (eg: using readlines() or something)
A list of responses where data is a list 
An already flattened object
A list of already flattened objects

ensure_flatten will always return a list of objects, and always attempt to expand anything that has `data` - regardless of what's inside includes or not, so it will work for both tweets and users, eg:

```
twarc2 following overflow64 | twarc2 flatten
```

**Pull request merged**
