### PR TITLE
Add a searches function, that executes multiple searches from an inpu…

### LINKED ISSUE #528: CLI entrypoint for running multiple searches
There are a few common use cases that can be boiled down to "run many searches" - think of retrieving the mentions for lots of different accounts, or searching for lots of keywords or phrases that wouldn't otherwise fit into a single search.

It would be nice if there were a `twarc2 searches` command that works similarly to the timelines command, taking an input file with one line per query, and working through the list to retrieve everything.

It would be even nicer if it batched and concatenated queries up to the character limit, to minimise the number of API calls made.

### PR DESCRIPTION
**Pull request by SamHames**
…t file

Closes #528

### CODE REVIEW

**Comment by SamHames** [comment]
I'm still not completely sure about the interface to this - but it does let you specify a bunch of searches in an input file, and includes the option to do a dryrun with the counts function first. Some more testing is needed.

**Comment by SamHames** [comment]
Would appreciate a second set of eyes on this one now. I think it's ready to go, but the design adds an inconsistency in command names: we currently have `search` and `counts`, and this add `searches` which does both of those with a command line switch (`--counts-only`). I went with the flag instead of a separate command because I couldn't think of a name that made sense for a counts-driven-by-file command (search -> searches, count->countses?).

The --combine-queries option is meant to allow merging a set of queries using a disjunction, so you make fewer API calls.

**Comment by edsu** [comment]
This looks very thorough @SamHames and works well ... it almost makes me wonder if search should have --counts-only instead of there being a separate command. The `--combine_queries` idea is pretty ingenious! :-)

**Review by edsu — APPROVED** [review]
This looks good Sam! I'm curious, did the idea for this come from a user request?

**Comment by SamHames** [comment]
Yeah, the idea originally came from discussion in the Docnow slack - but I kept talking to people where it would save more complicated scripting so thought I'd get it done :)

**Pull request merged**
