### PR TITLE
Support gnip full archive search

### PR DESCRIPTION
**Pull request by epicfaace**
Support full archive search with the gnip twitter enterprise API.

This PR probably still needs some cleanup (and tests), but wanted to get feedback on the authentication mechanism that was needed.

### CODE REVIEW

**Comment by edsu** [comment]
Wow, this is super @epicfaace! I didn't realize GNIP was still a thing, I thought it was replaced by their [Enterprise API](https://developer.twitter.com/en/products/twitter-api/enterprise). But since I don't have access to that I've never known what it was.

Would you be willing to add a little unit test that is skipped if the GNIP environment isn't present? You can see an example of this at the bottom of the test file for the Premium API tests.

**Comment by epicfaace** [comment]
Sure, will do.

**Comment by epicfaace** [comment]
@edsu I've added that test; however, I've temporarily lost access to GNIP so I can't actually verify that it works.

Some further things beyond this PR that I think would be nice:
- interactively configure GNIP credentials by running `twarc configure --gnip_auth`
- adding mock API responses so that we can run GNIP / premium / other tests on CI without needing to use API keys

Let me know if you are good with these proposals, and I'll probably add them in other PRs when I get some time.

**Comment by edsu** [comment]
Awesome, thanks for doing that @epicfaace -- if you don't mind too much lets wait until you can verify the tests work before merging this. Maybe someone else with access to the full archive can take a look?

**Comment by epicfaace** [comment]
Okay, I was just able to verify that the test works:

image

**Comment by edsu** [comment]
So awesome, thanks for all this work @epicfaace it is super appreciated!

**Comment by edsu** [comment]
Ok thais was just released as part of v1.12.0. Since it didn't add the 30 day Gnip endpoint I might change things in the future. But I think this is very nice to have for the few people who have access to this service.

**Comment by epicfaace** [comment]
Great, thanks!

**Pull request merged**
